# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://api.spacetraders.io/v2/systems/X1-KA58/waypoints/X1-KA58-B7/market

###
GET https://api.spacetraders.io/v2/my/ships
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA



###
GET https://api.spacetraders.io/v2/my/ships/MIKETHEMAGE-1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA


###
POST https://api.spacetraders.io/v2/my/ships/MIKETHEMAGE-1/orbit
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA

###
POST https://api.spacetraders.io/v2/my/ships/MIKETHEMAGE-1/navigate
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA
Content-Type: application/json

{
  "waypointSymbol": "X1-KA58-B7"
}


###
POST https://api.spacetraders.io/v2/my/ships/MIKETHEMAGE-2/orbit
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA


###
POST https://api.spacetraders.io/v2/my/ships/MIKETHEMAGE-2/survey
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiTUlLRVRIRU1BR0UiLCJ2ZXJzaW9uIjoidjIuMi4wIiwicmVzZXRfZGF0ZSI6IjIwMjQtMDMtMjQiLCJpYXQiOjE3MTEzOTA1MDMsInN1YiI6ImFnZW50LXRva2VuIn0.MV2A62Sg2e6U2Sm4EskPrgFrKRx3BSeM-bcgxD3o4ATcr-eoGB5LgsL9sGA0Zd0gdhNVcXEN2mKL3zMyzABDEzo1yaMcpY2Rc9STQC3_cBY7zV7y9OOtYAhC2cEVlX4z237afH8L_PoS8zqSfHVXAqWEUxR131rQPoBdjsjU6vgQW2KOHB_R3avhsbHzD2YjxUmbJNzcQ48pOUBcAN_2CnVO3FZ0JSnyNZIdumS8g4safvfWt_p4v9D3QR9l5nu8a5ilHZsKUwwfSEuaywS8Yqhk3SvPvFpn04WH87N05lQ7PThJg90xx9zahmq5zbeYWMXWamSLffNmwpHpadW6pA
